# Generated by Django 5.2 on 2025-08-16 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='vocalforlocal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.URLField()),
                ('logo', models.URLField(default='please upload logo')),
                ('interestincontent', models.CharField(default='Get Festive ready', max_length=100)),
                ('offer', models.DecimalField(decimal_places=0, max_digits=2)),
            ],
        ),
    ]
