# Generated by Django 5.2 on 2025-08-16 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fashion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='vocalforlocal1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.URLField()),
                ('logo1', models.URLField(default='please upload logo')),
                ('interestincontent1', models.CharField(default='Get Festive ready', max_length=100)),
                ('offer1', models.DecimalField(decimal_places=0, max_digits=2)),
            ],
        ),
        migrations.CreateModel(
            name='vocalforlocal2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image2', models.URLField()),
                ('logo2', models.URLField(default='please upload logo')),
                ('interestincontent2', models.CharField(default='Get Festive ready', max_length=100)),
                ('offer2', models.DecimalField(decimal_places=0, max_digits=2)),
            ],
        ),
    ]
