# Generated by Django 5.2 on 2025-08-16 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fashion', '0002_vocalforlocal1_vocalforlocal2'),
    ]

    operations = [
        migrations.CreateModel(
            name='shopclothing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageshopclothing', models.URLField()),
                ('contentshopclothing', models.CharField(default='tops & t-shirts', max_length=100)),
                ('priceshopclothing', models.DecimalField(decimal_places=0, max_digits=2)),
            ],
        ),
    ]
