# Generated by Django 5.2 on 2025-08-16 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fashion', '0003_shopclothing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopclothing',
            name='priceshopclothing',
            field=models.DecimalField(decimal_places=0, max_digits=5),
        ),
    ]
