# Generated by Django 5.2 on 2025-08-16 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fashion', '0004_alter_shopclothing_priceshopclothing'),
    ]

    operations = [
        migrations.CreateModel(
            name='shopfootwear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageshopfootwear', models.URLField()),
                ('contentshopfootwear', models.CharField(default='tops & t-shirts', max_length=100)),
                ('priceshopfootwear', models.DecimalField(decimal_places=0, max_digits=5)),
            ],
        ),
    ]
