# Generated by Django 5.2 on 2025-08-17 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fashion', '0005_shopfootwear'),
    ]

    operations = [
        migrations.AddField(
            model_name='vocalforlocal',
            name='price',
            field=models.DecimalField(decimal_places=0, default='499', max_digits=5),
        ),
        migrations.AddField(
            model_name='vocalforlocal1',
            name='price1',
            field=models.DecimalField(decimal_places=0, default='499', max_digits=5),
        ),
        migrations.AddField(
            model_name='vocalforlocal2',
            name='price2',
            field=models.DecimalField(decimal_places=0, default='499', max_digits=5),
        ),
    ]
