# Generated by Django 5.2 on 2025-08-17 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fashion', '0006_vocalforlocal_price_vocalforlocal1_price1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget_Add_Ons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageshopBudget', models.URLField()),
                ('contentshopBudget', models.CharField(default='tops & t-shirts', max_length=100)),
                ('priceshopBudget', models.DecimalField(decimal_places=0, max_digits=5)),
            ],
        ),
    ]
