# Generated by Django 5.2 on 2025-08-17 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fashion', '0007_budget_add_ons'),
    ]

    operations = [
        migrations.CreateModel(
            name='shopBeauty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageshopBeauty', models.URLField()),
                ('contentshopBeauty', models.CharField(default='skincare', max_length=100)),
                ('priceshopBeauty', models.DecimalField(decimal_places=0, max_digits=5)),
            ],
        ),
    ]
