# Generated by Django 5.2 on 2025-07-15 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mainob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(default='bazaar', max_length=500)),
                ('imagemain', models.URLField()),
            ],
        ),
    ]
