# Generated by Django 5.2 on 2025-07-15 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobileviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainob',
            name='image',
            field=models.URLField(default='please upload non-background image'),
        ),
    ]
