# Generated by Django 5.2 on 2025-07-15 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobileviews', '0002_mainob_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainob',
            name='crazylower',
            field=models.CharField(default='crazylowerprice', max_length=200),
        ),
    ]
