# Generated by Django 5.2 on 2025-07-15 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobileviews', '0003_mainob_crazylower'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainob',
            name='term',
            field=models.CharField(default='T&C apply', max_length=100),
        ),
    ]
