# Generated by Django 5.2 on 2025-07-15 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobileviews', '0004_mainob_term'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainob',
            name='startingprice',
            field=models.CharField(default='starting 199', max_length=100),
        ),
    ]
