# Generated by Django 5.2 on 2025-07-15 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobileviews', '0005_mainob_startingprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainob',
            name='name',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
