# Generated by Django 5.2 on 2025-07-15 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobileviews', '0007_alter_mainob_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainob',
            name='name',
            field=models.CharField(default='white bags', max_length=100),
        ),
    ]
