# Generated by Django 5.2 on 2025-07-15 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobileviews', '0009_alter_mainob_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainob',
            name='name',
            field=models.CharField(blank=True, default='white bags', max_length=100, null=True),
        ),
    ]
