# Generated by Django 5.2 on 2025-07-15 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobileviews', '0011_alter_mainob_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainob',
            name='imagemain',
            field=models.URLField(default='https://via.placeholder.com/300'),
        ),
    ]
