# Generated by Django 5.2 on 2025-07-15 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobileviews', '0012_alter_mainob_imagemain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainob',
            name='imagemain',
            field=models.URLField(default='upload image'),
        ),
    ]
