# Generated by Django 5.2 on 2025-07-15 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobileviews', '0014_alter_mainob_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainob',
            name='name',
        ),
    ]
