# Generated by Django 5.2 on 2025-07-15 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobileviews', '0015_remove_mainob_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainob',
            name='name',
            field=models.CharField(blank=True, default='Unknown', max_length=100, null=True),
        ),
    ]
