# Generated by Django 5.2 on 2025-07-15 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobileviews', '0016_mainob_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='cartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(default='store etc', max_length=100)),
                ('price', models.DecimalField(decimal_places=2, default='250', max_digits=10)),
                ('quantity', models.IntegerField(default=1)),
                ('off174', models.DecimalField(decimal_places=2, default='10', max_digits=10)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mobileviews.mainob')),
            ],
        ),
    ]
