# Generated by Django 5.2 on 2025-07-15 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobileviews', '0017_cartitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainob',
            name='startingprice',
            field=models.DecimalField(decimal_places=2, default='starting 199', max_digits=100),
        ),
    ]
