# Generated by Django 5.2 on 2025-07-16 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobileviews', '0019_remove_cartitem_product_alter_cartitem_off174_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='cartItem',
            new_name='cartItemMobile',
        ),
    ]
