# Generated by Django 5.2 on 2025-07-16 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobileviews', '0020_rename_cartitem_cartitemmobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='mainob2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(default='please fill this field', max_length=200)),
                ('imagemainob2', models.URLField()),
            ],
        ),
    ]
