# Generated by Django 5.2 on 2025-07-16 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobileviews', '0021_mainob2'),
    ]

    operations = [
        migrations.CreateModel(
            name='mainob3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('footer', models.CharField(default='fill', max_length=200)),
                ('imagemainob3', models.URLField()),
            ],
        ),
    ]
