# Generated by Django 5.2 on 2025-07-16 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobileviews', '0022_mainob3'),
    ]

    operations = [
        migrations.CreateModel(
            name='mainob4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('footer1', models.CharField(default='fill', max_length=200)),
                ('offer1', models.DecimalField(decimal_places=1, max_digits=10)),
                ('image4m1', models.URLField()),
                ('footer2', models.CharField(default='fill', max_length=200)),
                ('offer2', models.DecimalField(decimal_places=1, max_digits=10)),
                ('image4m2', models.URLField()),
                ('footer3', models.CharField(default='fill', max_length=200)),
                ('offer3', models.DecimalField(decimal_places=1, max_digits=10)),
                ('image4m3', models.URLField()),
                ('footer4', models.CharField(default='fill', max_length=200)),
                ('offer4', models.DecimalField(decimal_places=1, max_digits=10)),
                ('image4m4', models.URLField()),
            ],
        ),
    ]
