# Generated by Django 5.2 on 2025-07-24 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobileviews', '0023_mainob4'),
    ]

    operations = [
        migrations.CreateModel(
            name='bestseller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headermatch', models.CharField(default='bestseller', max_length=200)),
                ('headermatch_slug', models.SlugField(blank=True, unique=True)),
                ('Imagem', models.URLField()),
                ('contentm', models.CharField(default='name of watches', max_length=300)),
                ('pricewacth', models.DecimalField(decimal_places=1, max_digits=10)),
            ],
        ),
    ]
