# Generated by Django 5.2 on 2025-07-24 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobileviews', '0024_bestseller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bestseller',
            name='headermatch_slug',
        ),
    ]
