# Generated by Django 5.2.7 on 2025-11-03 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobileviews', '0025_remove_bestseller_headermatch_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='mainob4',
        ),
    ]
