# Generated by Django 5.2.7 on 2025-11-03 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobileviews', '0026_delete_mainob4'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainob',
            name='startingprice',
            field=models.DecimalField(decimal_places=0, default='starting 199', max_digits=100),
        ),
    ]
