# Generated by Django 5.2 on 2025-08-17 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bedroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.URLField()),
                ('content', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=0, max_digits=5)),
            ],
        ),
    ]
