# Generated by Django 5.2 on 2025-07-02 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='main',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bgimage', models.URLField()),
                ('heading', models.CharField(max_length=200)),
                ('heading2', models.CharField(max_length=200)),
                ('paragraph', models.CharField(default='Top brands', max_length=200)),
                ('paragraph2', models.CharField(default='Term and condition', max_length=200)),
                ('bgimage2', models.URLField()),
            ],
        ),
    ]
