# Generated by Django 5.2 on 2025-07-02 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maincontainer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='Term',
            field=models.CharField(default='Term and condition', max_length=200),
        ),
        migrations.AlterField(
            model_name='main',
            name='paragraph2',
            field=models.CharField(default='Latest brands', max_length=200),
        ),
    ]
