# Generated by Django 5.2 on 2025-07-02 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maincontainer', '0002_main_term_alter_main_paragraph2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main',
            name='bgimage2',
            field=models.URLField(default='please fill the bg removal image'),
        ),
    ]
