# Generated by Django 5.2 on 2025-07-02 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maincontainer', '0003_alter_main_bgimage2'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=200)),
                ('image1', models.URLField()),
                ('content1', models.CharField(default='Air conditioner', max_length=100)),
                ('image2', models.URLField()),
                ('content2', models.CharField(default='refgeritor', max_length=100)),
                ('image3', models.URLField()),
                ('content3', models.CharField(default='Microwaves', max_length=100)),
                ('image4', models.URLField()),
                ('content4', models.CharField(default='washing machines', max_length=100)),
            ],
        ),
    ]
