# Generated by Django 5.2 on 2025-07-03 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maincontainer', '0004_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='actiontoys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header1', models.CharField(max_length=200)),
                ('actionimage', models.URLField()),
            ],
        ),
    ]
