# Generated by Django 5.2 on 2025-07-03 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maincontainer', '0005_actiontoys'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actiontoys',
            name='header1',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
