# Generated by Django 5.2 on 2025-07-03 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maincontainer', '0006_alter_actiontoys_header1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actiontoys',
            name='header1',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
