# Generated by Django 5.2 on 2025-07-03 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maincontainer', '0007_alter_actiontoys_header1'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price1',
            field=models.DecimalField(decimal_places=2, default='100', max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='price2',
            field=models.DecimalField(decimal_places=2, default='100', max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='price3',
            field=models.DecimalField(decimal_places=2, default='100', max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='price4',
            field=models.DecimalField(decimal_places=2, default='100', max_digits=10),
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maincontainer.product')),
            ],
        ),
    ]
