# Generated by Django 5.2 on 2025-07-10 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maincontainer', '0008_product_price1_product_price2_product_price3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='content',
            field=models.CharField(default='store etc', max_length=100),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default='250', max_digits=10),
        ),
    ]
