# Generated by Django 5.2 on 2025-07-12 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maincontainer', '0009_cartitem_content_cartitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='off171',
            field=models.DecimalField(decimal_places=2, default='10', max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='off172',
            field=models.DecimalField(decimal_places=2, default='10', max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='off173',
            field=models.DecimalField(decimal_places=2, default='10', max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='off174',
            field=models.DecimalField(decimal_places=2, default='10', max_digits=10),
        ),
    ]
