# Generated by Django 5.2 on 2025-07-12 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maincontainer', '0010_product_off171_product_off172_product_off173_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='off174',
            field=models.DecimalField(decimal_places=2, default='10', max_digits=10),
        ),
    ]
