# Generated by Django 5.2 on 2025-07-12 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maincontainer', '0011_cartitem_off174'),
    ]

    operations = [
        migrations.CreateModel(
            name='mobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header2', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('imagemobile', models.URLField()),
                ('offermobile', models.CharField(default='44off', max_length=150)),
                ('pricem', models.DecimalField(decimal_places=2, default='70', max_digits=10)),
                ('mrpmobile', models.DecimalField(decimal_places=2, default='80', max_digits=10)),
                ('nameofmobile', models.CharField(default=None, max_length=200, null=True)),
            ],
        ),
    ]
