# Generated by Django 5.2 on 2025-07-13 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maincontainer', '0012_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobile',
            name='offermobile',
            field=models.DecimalField(decimal_places=2, default='44off', max_digits=10),
        ),
    ]
