# Generated by Django 5.2 on 2025-07-13 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maincontainer', '0013_alter_mobile_offermobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='maincontainer.product'),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='offermobile',
            field=models.DecimalField(decimal_places=2, default='44', max_digits=10),
        ),
    ]
