# Generated by Django 5.2 on 2025-07-14 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maincontainer', '0014_alter_cartitem_product_alter_mobile_offermobile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mobile',
            name='pricem',
        ),
    ]
