# Generated by Django 5.2 on 2025-07-24 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maincontainer', '0016_bestseller'),
    ]

    operations = [
        migrations.DeleteModel(
            name='bestseller',
        ),
    ]
