# Generated by Django 5.2 on 2025-08-01 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maincontainer', '0017_delete_bestseller'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fresh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bgimagefresh', models.URLField()),
                ('vegitablebimagefresh', models.URLField()),
                ('nameoffresh', models.CharField(default='best quality', max_length=100)),
                ('headingfresh1', models.CharField(default='100 fresh', max_length=150)),
                ('paragraphfresh', models.CharField(default='fresh products', max_length=100)),
                ('paragraphfresh1', models.CharField(default='fresh', max_length=100)),
                ('pricefresh', models.DecimalField(decimal_places=1, max_digits=10)),
                ('offerfresh', models.DecimalField(decimal_places=1, max_digits=5)),
            ],
        ),
    ]
