# Generated by Django 5.2 on 2025-08-01 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maincontainer', '0018_fresh'),
    ]

    operations = [
        migrations.AddField(
            model_name='fresh',
            name='Termfresh',
            field=models.CharField(default='Term and condition', max_length=200),
        ),
    ]
