# Generated by Django 5.2 on 2025-08-01 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maincontainer', '0019_fresh_termfresh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fresh',
            name='headingfresh1',
            field=models.CharField(default='fresh quality', max_length=150),
        ),
        migrations.AlterField(
            model_name='fresh',
            name='nameoffresh',
            field=models.CharField(default='name of vegitables', max_length=100),
        ),
        migrations.AlterField(
            model_name='fresh',
            name='paragraphfresh',
            field=models.CharField(default='Eat Green, Life Green', max_length=100),
        ),
        migrations.AlterField(
            model_name='fresh',
            name='paragraphfresh1',
            field=models.CharField(default='100% fresh product available', max_length=100),
        ),
    ]
