# Generated by Django 5.2 on 2025-08-04 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maincontainer', '0020_alter_fresh_headingfresh1_alter_fresh_nameoffresh_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='mainmobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mainimagemobile', models.URLField()),
                ('nameofmmobile', models.CharField(default='mobile with models', max_length=200)),
                ('specsofmmobileRamrom', models.CharField(default='Titanium, 6GB RAM, 128GB Storage', max_length=200)),
                ('specsofbattery', models.CharField(default='6500 mAh Large Capacity Battery', max_length=200)),
                ('specsfofprocessor', models.CharField(default='Dimensity 7300 Processor', max_length=200)),
                ('specsofdurability', models.CharField(default='Military-Grade Durability', max_length=200)),
                ('mainmratings', models.DecimalField(decimal_places=0, max_digits=4)),
                ('mainmdeals', models.CharField(default='freedom sale deals', max_length=100)),
                ('mainmprice', models.DecimalField(decimal_places=0, max_digits=6)),
                ('mainmmrp', models.DecimalField(decimal_places=0, max_digits=6)),
                ('mainmoffer', models.DecimalField(decimal_places=0, max_digits=2)),
                ('mainmofferoncreditcard', models.DecimalField(decimal_places=0, max_digits=2)),
            ],
        ),
    ]
