# Generated by Django 5.2 on 2025-08-04 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maincontainer', '0021_mainmobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainmobile',
            name='mainmtodaydate',
            field=models.DateField(auto_now=True),
        ),
    ]
