# Generated by Django 5.2 on 2025-08-04 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maincontainer', '0022_mainmobile_mainmtodaydate'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainmobile',
            name='bgmainimagembile',
            field=models.URLField(default='black background image of marvels'),
        ),
    ]
