# Generated by Django 5.2 on 2025-08-04 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maincontainer', '0023_mainmobile_bgmainimagembile'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainmobile',
            name='specsofcamera',
            field=models.CharField(default='50MP + 2MP - 16MP Front Camera ', max_length=100),
        ),
    ]
