# Generated by Django 5.2 on 2025-08-05 11:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maincontainer', '0024_mainmobile_specsofcamera'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainmobile',
            name='mainmtodaydate',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
