# Generated by Django 5.2 on 2025-08-07 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maincontainer', '0025_alter_mainmobile_mainmtodaydate'),
    ]

    operations = [
        migrations.CreateModel(
            name='electronicslaptop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('laptopname', models.CharField(default='name of laptop', max_length=100)),
                ('laptopimage', models.URLField()),
                ('laptopoffer', models.DecimalField(decimal_places=0, max_digits=2)),
                ('laptopmrpprice', models.DecimalField(decimal_places=0, max_digits=5)),
            ],
        ),
    ]
