# Generated by Django 5.2 on 2025-08-11 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maincontainer', '0026_electronicslaptop'),
    ]

    operations = [
        migrations.CreateModel(
            name='electronicsheadphones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headphonesname', models.CharField(default='name of laptop', max_length=100)),
                ('headphonesimage', models.URLField()),
                ('headphonesoffer', models.DecimalField(decimal_places=0, max_digits=2)),
                ('headphonesmrpprice', models.DecimalField(decimal_places=0, max_digits=5)),
            ],
        ),
    ]
