# Generated by Django 5.2 on 2025-08-12 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maincontainer', '0027_electronicsheadphones'),
    ]

    operations = [
        migrations.CreateModel(
            name='electronicsstored',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storedname', models.CharField(default='name of laptop', max_length=100)),
                ('storedimage', models.URLField()),
                ('storedoffer', models.DecimalField(decimal_places=0, max_digits=2)),
                ('storedmrpprice', models.DecimalField(decimal_places=0, max_digits=5)),
            ],
        ),
    ]
