# Generated by Django 5.2 on 2025-08-23 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maincontainer', '0030_datasave'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasave',
            name='session_otp',
            field=models.CharField(blank=True, default='000000', max_length=6),
        ),
        migrations.AddField(
            model_name='datasave',
            name='user_otp',
            field=models.CharField(blank=True, default='000000', max_length=6),
        ),
    ]
