# Generated by Django 5.2.7 on 2025-10-22 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maincontainer', '0031_datasave_session_otp_datasave_user_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='off174',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=10),
        ),
    ]
