# Generated by Django 5.2.7 on 2025-10-27 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maincontainer', '0032_alter_cartitem_off174'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.URLField()),
                ('content', models.CharField(max_length=200)),
                ('payment_method', models.CharField(default='UPI', max_length=50)),
                ('address', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
