# Generated by Django 5.2.7 on 2025-10-27 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maincontainer', '0034_useraddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='address',
            field=models.TextField(default='12'),
        ),
    ]
