# Generated by Django 5.2.7 on 2025-11-03 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maincontainer', '0035_useraddress_address'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
